### ISSUE TITLE
Mago arcano roto y desbalanceo general de todas las clases

### ISSUE THREAD

**Issue by hiromi41** [elerendon/Bugtracker-Monster-x12#1]
Buenas noches mi estimado dennis, me acerco a usted con el animo de informarle que el mago arcano esta pegando de 80k-100k en las bgs deleteando a todo el mundo pero no vengo aca para tirar meirda por eso sino vengo a pedirle por favor y de rodillas que devuelvan los daños del 4.3.4 retail ya que así el juego era muchísimo mas divertido y dinámico ya que o oneshoteabas o te oneshoteaban fin , créame que toda la comunidad le estará infinitamente agradecido si este fuera el caso

Desde ya le agradezco su atencion

pd: No se si ya reportaron que el vendedor de puntos de honor no esta vendiendo enchants para el hombro y la cabeza 

me despido att: un fiel seguidor de monster <3

**Comment by elerendon** [comment]
se necesita nombre de las habilidades para poder nerfear dichos poderes rotos de los magos

**Comment by hiromi41** [comment]
No lo que yo busco no es que no nerfeen sino que nos devuelvan el daño a todos, ya que esto esta explotando en un desbalance terrible en todos las clases

**Comment by elerendon** [comment]
yo necesito fixear clase por clase para que haya un balance correcto y nerfear las habilidades que estan muy subidas de lo contrario no podré hacer nada y daré por cerrado este reporte ya que no queremos un servidor donde el pvp sea oneshot, buscamos un balance nerfeando a las habilidades que pegan exageradamente.

**Comment by hiromi41** [comment]
Entonces nerfeen el escudo del sacer y la curación del espiral de la muerte del dk que se cura exageradamente

**Comment by Andrewmusso** [comment]
no solo es el magos tmbn los sacers que con 2 doits ya tienes la mitad de vida en cuento los magos que esta desbalanceado probé al mago mago fuego con dichas habilidades piroexplocion , agostar, bomba viva
