### ISSUE TITLE
mision de los kalu ak

### ISSUE THREAD

**Issue by barkano** [elerendon/Bugtracker-Monster-x12#10]
https://www.wowhead.com/wotlk/es/quest=12032/conversing-with-the-depths#guides al saltar no cuenta como completada ya intente de todos las formas q encontre en internet y no dio

**Comment by elerendon** [comment]
![image](https://user-images.githubusercontent.com/42742610/194379421-d382888f-3ac1-4a41-940b-1f63b1d80597.png)
autocompletable de momento, abandonarla y volverla a tomar

**Comment by barkano** [comment]
no quiere completar

**Comment by barkano** [comment]
@elerendon no pueo tomar la mision ni completr estoy como mimove
