### ISSUE TITLE
bug LAS FAUCES DE ISO´RATH

### ISSUE THREAD

**Issue by felizan2003** [elerendon/Bugtracker-Monster-x12#11]
https://es.wowhead.com/quest=27376/las-fauces-de-isorath

la mision se encuentra bug por la cantidad inhumana de bichos que hay en la zona, no permite hablar con el NPC el clamatormentas yevaa, y por ende nop se puede hacr nada en la zona, los adds matan los NPC y pues f

**Comment by elerendon** [comment]
![image](https://user-images.githubusercontent.com/42742610/194381123-586c595e-0a80-4e24-a91b-51c7bf234da3.png)
npcs en exceso removidos
