### ISSUE TITLE
Mision "Peticion de Refuerzos" Monte Hyjal

### ISSUE THREAD

**Issue by Kalormorth** [elerendon/Bugtracker-Monster-x12#16]
Esta mision nos dice lo siguiente: Obten 20 marcas del Arbol del Mundo. 
Las cuales consigues haciendo diarias del Monte Hyjal siendo mas preciso en el Santurio de Malorne. Alli realice las diarias hasta obtener las 20 marcas las cuales ya tengo con el personaje pero esta misma mision no me deja completarla por las marcas que junte no puedo proseguir con la secuencia.

**Comment by Kalormorth** [comment]
![imagen_2022-10-05_234822191](https://user-images.githubusercontent.com/114854397/194224272-eba5c511-db9d-41b6-88f3-bb7f63098a62.png)

**Comment by elerendon** [comment]
![image](https://user-images.githubusercontent.com/42742610/194384298-f219e113-63ad-4eb8-96ac-34d5c2992797.png)
la mision funciona correctamente, al tomar la mision tienes que si o si obtener las 20 marcas, no vale si ya las tienes, toca conseguir 20 extras.
