### ISSUE TITLE
NPC DEL EVENTO HALLOWEEN NO SE ENCUENTRAN faccion (HORDA)

### ISSUE THREAD

**Issue by stoper90** [elerendon/Bugtracker-Monster-x12#26]
no se encuentra los npc de halloween para la (horda) que se deberian encontrar en (Entrañas)
no esta el ( MUÑECO DE MIMBRE, LOS MERCADERES, LOS NPC DE MISIONES DIARIAS) por favor se les agradeceria mucho que lo pongan porque en pocas palabras entrañas esta vacio.
![WoWScrnShot_101922_201616](https://user-images.githubusercontent.com/90732987/196828787-c2bf083d-18a7-4887-b0da-961a8a45608e.jpg)

**Comment by elerendon** [comment]
se necesita nombre del npc, id link de wow head y video de referencia para solucionarlo el proximo año
