### ISSUE TITLE
Bug de pj que cierra el wow de manera inesperada

### ISSUE THREAD

**Issue by Idkjuanito** [elerendon/Bugtracker-Monster-x12#27]
Personaje: Kaisha
Usuario de DC: Yasurdo_

Al intentar a un pj que esta en una zona especifica del mundo (Terrallende, peninsula de fuego infernal) el juego se cierra sin mas, no muestra ventana de error, tampoco ningun tipo de mensaje, solo se cierra y ya

**Comment by elerendon** [comment]
descargar denuevo el runplay, actualizar tus drivers y mejorar el rendimiento de la pc.
