### ISSUE TITLE
DK no ataca, no puedo obtener misiones y no ay npc

### ISSUE THREAD

**Issue by Atenea20** [elerendon/Bugtracker-Monster-x12#28]
Hola al hacer la última misión de DK me lanzó a los portales, me fui a ventormenta y despues a diarias y me di cuenta de que no puedo atacar ni seleccionar enemigos, regrese ala ciudadela de los DK para ver si algo me faltó pero nadie me da misiones y veo pocos npc necesito ayuda mi pj ateneatanke
ID Alecaz13

**Comment by elerendon** [comment]
necesitas terminar la última misión de los dk para poder salir del apaciguado
