### ISSUE TITLE
Al servicio de los illidari mision bug

### ISSUE THREAD

**Issue by Plinshi** [elerendon/Bugtracker-Monster-x12#29]
Luego de terminar la mision previa de rescatar a la dragona, el NPC Mordenai no da la siguiente mision "al servicio de los illidari" 
 ( https://www.wowhead.com/tbc/es/quest=11013/al-servicio-de-los-illidari )la cual permite disfrazarnos de orco y seguir con las misiones de reputacion de la faccion ala abisal.

**Comment by elerendon** [comment]
esa misión se realiza cuando eres exaltado con dicha facción
