### ISSUE TITLE
Unos bug

### ISSUE THREAD

**Issue by jorgehur** [elerendon/Bugtracker-Monster-x12#32]
Buenas, al momento de empesar las quest de las tierras altas crepusculares encontre un bug, una vez aceptada la quest me pidio ir al castillo de ventormenta a hablar con Varian ![prueba1](https://user-images.githubusercontent.com/57196444/201564772-89fbd502-c678-4ef2-9ea7-d098ff544ed6.PNG)
lo cual hize y me dijo que me dirigiera al puerto, pero antes habian 2 misiones al costado de el de su hijo, uno de su forma de infante y el otro que anda con su grifo, una vez acabado estas 2 fui al puerto de ventormenta 
![prueba2](https://user-images.githubusercontent.com/57196444/201564823-1d21e86c-0261-4343-bf2e-086092c8eef9.PNG)
donde me pidieron recoger 5 cajas que se encontraban por ahi, lo cual hize y la quest desaparecio sola y luego no habia no aparecieron mas quest y cuando voy a las tierras alta crepusuclares no hay ninguna mision disponible, aparte de algunas que era para matar en una arena.
Luego otro problema en el monte hyjal que este npc aparece en dos ubicaciones con la quest asi
![prueba3](https://user-images.githubusercontent.com/57196444/201565288-2ff00a2e-fe0c-4038-a561-89dc94d4297c.PNG)
![prueba4](https://user-images.githubusercontent.com/57196444/201565524-53ce8847-ec54-4510-b234-018aa19f10c5.PNG)

**Comment by elerendon** [comment]
las misiones de hyjal y de tierras altas son así, debes de buscar guias de youtube para continuar con las cadenas de misiones

**Comment by jorgehur** [comment]
lo de las tierras altas crepusculares, segun las guias en youtube era solo hablar con el cartel, luego con varian y luego ir al puerto a subirse a un avion, pero no aparece ese npc del avion
