### ISSUE TITLE
té de cardo no da la energía que debería dar

### ISSUE THREAD

**Issue by hiromi41** [elerendon/Bugtracker-Monster-x12#5]
<img width="448" alt="Screenshot_1" src="https://user-images.githubusercontent.com/112531019/189640637-3ee26572-dde9-4602-b76f-57f6dbad3be6.png">
<img width="332" alt="Screenshot_2" src="https://user-images.githubusercontent.com/112531019/189640646-263aab69-d5ee-48c9-890e-364f5beae0b3.png">

El té de cardo regenera 10 de energía y no 100 como lo dice wow head

**Comment by hiromi41** [comment]
![image](https://user-images.githubusercontent.com/112531019/189640972-96963c93-ba64-4a7a-a6bb-c841ffa49324.png)

**Comment by elerendon** [comment]
ya funciona correctamente

**Comment by elerendon** [comment]
![image](https://user-images.githubusercontent.com/42742610/194391010-9a7aba22-f84f-44c7-b286-3cfcc1261550.png)
