### ISSUE TITLE
MISIÓN PENÍNSULA DEL FUEGO INFERNAL 

### ISSUE THREAD

**Issue by Ladysylvanas** [elerendon/Bugtracker-Monster-x12#9]
https://es.wowhead.com/quest=10208/perturbar-sus-refuerzos, esta misión no funciona, aunque tengas las piedras rúnicas necesarias no hace nada.

**Comment by elerendon** [comment]
![image](https://user-images.githubusercontent.com/42742610/194377672-99007ca8-df8c-4988-9b72-625eb4d0854b.png)
abandonar la mision y volverla a tomar, autocompletable de momento
